default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payroll_development
  username: 
  password:   

test:
  <<: *default
  database: payroll_test

production:
  <<: *default
  database: payroll_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>